### ISSUE TITLE
DataContext suggestions show compiler generated classes in the dropdown

### ISSUE THREAD

**Issue by davidwangms** [jbruening/ugui-mvvm#25]
The dropdown appears to be showing compiler generated classes as well, which may be confusing for the user, and also bloats up the suggestions box. These should be marked with CompilerGeneratedAttribute, so they can be filtered out from the results

![image](https://user-images.githubusercontent.com/51718780/62578642-7b7d0580-b856-11e9-889c-d0f14c00274d.png)

**Comment by ryantrem** [comment]
Good callout. I think filtering on that attribute could be done here: [PropertyPathSuggestionProvider.cs (line 158)](../blob/master/src/Assets/ugui-mvvm/Editor/PropertyPathSuggestionProvider.cs#L158). @davidwangms - any interest in taking a stab at a fix? 🙂

**Comment by davidwangms** [comment]
Could be interesting, I'll take a stab at it next week if no one else is around to look into it, sure

**Comment by AdamMitchell-ms** [comment]
@davidwangms , you can probably do this by adding a Where clause to that line which checks for [GeneratedCodeAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.codedom.compiler.generatedcodeattribute?view=dotnet-uwp-10.0).

Something like this:

>                 .Where(p => p.GetCustomAttribute<GeneratedCodeAttribute>() == null);


Haven't tested this code.

**Comment by AdamMitchell-ms** [comment]
Just noticed that you already found another attribute.  I'm not very familiar with the two, but I found this old blog post about them.
https://blogs.msdn.microsoft.com/codeanalysis/2007/04/27/correct-usage-of-the-compilergeneratedattribute-and-the-generatedcodeattribute/

**Comment by ryantrem** [comment]
Sounds to me like we should consider filtering out properties with any of the following attributes:
`CompilerGeneratedAttribute`
`GeneratedCodeAttribute`
`DebuggerNonUserCodeAttribute`
`EditorBrowsableAttribute` (with `EditorBrowsableState.Never`)
