### ISSUE TITLE
Can't build for UWP 

### ISSUE THREAD

**Issue by orshir** [jbruening/ugui-mvvm#3]
INPCBinding compilation fails when targeting UWP because IsValueType and BaseType are not supported. There is a way to overcome this using type.GetTypeInfo().BaseType instead of type.BaseType and the same for IsValueType. Should I submit a PR with a fix?

**Comment by jbruening** [comment]
Yes, if you can submit a PR with a fix that would be great.

**Comment by ryantrem** [comment]
@jbruening, this issue was resolved by @ritijain in PR #5.
