### ISSUE TITLE
Consider renaming INPCBinding to PropertyBinding

### ISSUE THREAD

**Issue by ryantrem** [jbruening/ugui-mvvm#7]
Designers on our team have expressed confusion with the name INPCBinding. Developers know what INotifyPropertyChanged is, but this doesn't mean anything to designers, and they have asked us why it isn't just named PropertyBinding (which they would understand, and would have a naming scheme more similar to CommandBinding). I think it would be great to change the name, especially if there is a way to do so without breaking existing assets (not sure how to do this when the class name changes).

@ritijain @mrw-eric

**Comment by AdamMitchell-ms** [comment]
If you rename the class/file but keep the .meta file with it and it uses the same guid as it had before the rename, then any game objects with that component attached to them will do the right thing.

Not sure if this works for anyone who consumes this in a project via compiled dlls.  And it won't work for any external scripts that reference the class by name.

All that said, I agree that PropertyBinding seems more user-friendly.

**Comment by MRW-Eric** [comment]
We should do this sooner than later because it is being implemented in several projects. Property Binding 2019!

**Comment by AdamMitchell-ms** [comment]
This change is now in.
