### ISSUE TITLE
INPCBinding fail if disabled before Start and enabled after DataContext is attached

### ISSUE THREAD

**Issue by davidwangms** [jbruening/ugui-mvvm#9]
**Repro Steps**

1. Create a hierarchy where an INPCBinding exists on a disabled gameObject
2. Assign a DataContext
3. Re-enable the gameObject hierarchy which contains the INPCBinding

**Actual**
INPCBinding will not bind to the ViewModel properly

**Expected**
INPCBinding should still bind to the view model

**Investigation**
INPCBindings register with the DataContext on Start(), and the bindings to the ViewModel are only done when the DataContext is set. This means that disabled INPCBindings will not be registered with the DataContext when ViewModels are set, and so will not be subscribed to the INPC event.

One workaround right now is to have a helper that rebinds the DataContext when one of these object hierarchies is enabled for the first time. However, it would be expected that new bindings that are registered while a DataContext is available should be bound immediately.

**Comment by ryantrem** [comment]
I think `INPCBinding::AddDependentProperty` just needs to call `AddHandler` and `TriggerHandler` like in `UpdateValue`.

**Comment by ryantrem** [comment]
@jbruening - this issue was resolved by @Alex-MSFT's PR (#10).
